# Generated by Django 3.0.2 on 2026-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='memo',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kakeibo',
            name='money',
            field=models.IntegerField(),
        ),
    ]
